# Generated by Django 2.2.2 on 2019-06-10 08:34

from django.db import migrations, models
import django.db.models.deletion
import sample.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baz', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baz', models.IntegerField()),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Bar')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bar',
            constraint=models.UniqueConstraint(fields=('id', 'baz'), name='unique_id_and_baz'),
        ),
        migrations.AddConstraint(
            model_name='foo',
            constraint=sample.models.ForeignKeyConstraint(columns=('bar_id', 'baz'), name='composite_fk', to_columns=('id', 'baz'), to_model=sample.models.Bar),
        ),
    ]
